# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-12 07:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Joke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redditId', models.CharField(max_length=10)),
                ('setup', models.CharField(max_length=200)),
                ('punchline', models.CharField(max_length=300)),
                ('rating', models.IntegerField(default=0)),
                ('votes', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_type', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=20)),
                ('attachments', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='joke',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Message'),
        ),
    ]
