# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-12 15:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20161112_0806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joke',
            old_name='redditId',
            new_name='reddit_id',
        ),
    ]
