# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-12 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20161112_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='joke',
            name='url',
            field=models.URLField(default='https://reddit.com/r/dadjoke'),
        ),
    ]
