# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-13 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_joke_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='joke',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
