# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-13 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_joke_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='joke',
            name='name',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
