# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-13 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_joke_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joke',
            name='punchline',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='joke',
            name='setup',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='joke',
            name='url',
            field=models.URLField(default='https://reddit.com/r/dadjokes', max_length=500),
        ),
    ]
