# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-13 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20161113_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joke',
            name='punchline',
            field=models.TextField(),
        ),
    ]
